#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Jetson Nano Flight Log Analyzer & Plotter for UAV NMPC Experiments.
Parses real-time CSV flight logs generated by data_logger_node in data/jetson_flyrecord/.
Outputs academic tracking metrics, energy consumption analysis, and multi-panel plots.

Usage:
    python3 scripts/analyze_jetson_csv.py [path_to_csv_file]
If no argument is given, it automatically selects the latest CSV in data/jetson_flyrecord/.
"""

import os
import sys
import glob
import math
import csv

def find_latest_csv(search_dir):
    if not os.path.exists(search_dir):
        return None
    csv_files = glob.glob(os.path.join(search_dir, "flight_log_*.csv"))
    if not csv_files:
        # Also check subdirectories or parent data directory
        csv_files = glob.glob(os.path.join(search_dir, "**", "flight_log_*.csv"), recursive=True)
    if not csv_files:
        return None
    latest_file = max(csv_files, key=os.path.getmtime)
    return latest_file

def load_csv_data(filepath):
    data = {}
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            for k, v in row.items():
                if k not in data:
                    data[k] = []
                try:
                    data[k].append(float(v))
                except ValueError:
                    data[k].append(v)
    return data

def calculate_rmse(errors):
    if not errors:
        return 0.0
    return math.sqrt(sum(e * e for e in errors) / len(errors))

def analyze_flight_data(filepath):
    print("=" * 75)
    print(f">> Analyzing Jetson Nano Flight CSV: {os.path.basename(filepath)}")
    print("=" * 75)

    data = load_csv_data(filepath)
    if "time_sec" not in data or len(data["time_sec"]) == 0:
        print("Error: CSV file contains no valid flight samples.")
        return None

    time_sec = data["time_sec"]
    total_duration = time_sec[-1] - time_sec[0]
    sample_count = len(time_sec)
    actual_rate = sample_count / total_duration if total_duration > 0 else 0.0

    # Separate Tracking Mode (mode == 2) from Hover Mode (mode == 1)
    mode_list = [int(m) for m in data.get("mode", [-1] * sample_count)]
    tracking_indices = [i for i, m in enumerate(mode_list) if m == 2]
    
    # If no mode 2 found, analyze entire active in-air window (where command_thrust > 0.3)
    if len(tracking_indices) > 30:
        eval_indices = tracking_indices
        eval_phase_name = "Phase 2 Trajectory Tracking"
    else:
        eval_indices = [i for i in range(sample_count) if data.get("cmd_thrust", [0]*sample_count)[i] > 0.3]
        if not eval_indices:
            eval_indices = list(range(sample_count))
        eval_phase_name = "Full Flight / Hover Phase"

    eval_duration = time_sec[eval_indices[-1]] - time_sec[eval_indices[0]]

    # 1. Position tracking errors
    err_x = [data["err_x"][i] for i in eval_indices]
    err_y = [data["err_y"][i] for i in eval_indices]
    err_z = [data["err_z"][i] for i in eval_indices]
    err_norm = [data["err_pos_norm"][i] for i in eval_indices]

    rmse_x = calculate_rmse(err_x)
    rmse_y = calculate_rmse(err_y)
    rmse_z = calculate_rmse(err_z)
    rmse_pos = calculate_rmse(err_norm)
    max_err_pos = max(err_norm) if err_norm else 0.0
    mean_err_pos = sum(err_norm) / len(err_norm) if err_norm else 0.0

    # 2. Attitude tracking
    roll_list = [data["roll_deg"][i] for i in eval_indices]
    pitch_list = [data["pitch_deg"][i] for i in eval_indices]
    yaw_list = [data["yaw_deg"][i] for i in eval_indices]

    # 3. Battery and Energy Consumption
    voltage_list = [data.get("voltage_v", [0]*sample_count)[i] for i in eval_indices]
    current_list = [data.get("current_a", [0]*sample_count)[i] for i in eval_indices]
    power_list = [data.get("power_w", [0]*sample_count)[i] for i in eval_indices]
    
    # Check if power is recorded, else compute from V * I
    if not any(power_list) and any(voltage_list) and any(current_list):
        power_list = [voltage_list[i] * current_list[i] for i in range(len(eval_indices))]

    mean_v = sum(voltage_list) / len(voltage_list) if voltage_list else 0.0
    mean_i = sum(current_list) / len(current_list) if current_list else 0.0
    mean_p = sum(power_list) / len(power_list) if power_list else 0.0
    
    # Cumulative energy in Joules and Watt-hours
    total_energy_j = 0.0
    for i in range(1, len(eval_indices)):
        idx_prev = eval_indices[i - 1]
        idx_curr = eval_indices[i]
        dt = time_sec[idx_curr] - time_sec[idx_prev]
        if 0.0 < dt < 1.0:
            total_energy_j += power_list[i] * dt
            
    total_energy_wh = total_energy_j / 3600.0

    # 4. NMPC Compute Solve Latency
    solve_times = [data.get("solve_time_ms", [0]*sample_count)[i] for i in eval_indices if data.get("solve_time_ms", [0]*sample_count)[i] > 0]
    mean_solve_ms = sum(solve_times) / len(solve_times) if solve_times else 0.0
    max_solve_ms = max(solve_times) if solve_times else 0.0

    print(f"\n📊 --- 1. Flight Overview & Logging Stats ---")
    print(f"  * Total Flight Time:     {total_duration:.2f} s ({sample_count} samples @ {actual_rate:.1f} Hz)")
    print(f"  * Evaluated Window:      {eval_phase_name} ({eval_duration:.2f} s, {len(eval_indices)} samples)")

    print(f"\n🎯 --- 2. Trajectory Tracking Accuracy (Academic Metrics) ---")
    print(f"  * 3D Position RMSE:      {rmse_pos:.4f} m")
    print(f"  *   - Axis X RMSE:       {rmse_x:.4f} m")
    print(f"  *   - Axis Y RMSE:       {rmse_y:.4f} m")
    print(f"  *   - Axis Z (Alt) RMSE: {rmse_z:.4f} m")
    print(f"  * Mean 3D Error:         {mean_err_pos:.4f} m | Max 3D Error: {max_err_pos:.4f} m")
    print(f"  * Attitude Envelope:     Roll: [{min(roll_list):.1f}°, {max(roll_list):.1f}°], Pitch: [{min(pitch_list):.1f}°, {max(pitch_list):.1f}°]")

    print(f"\n⚡ --- 3. Power & Energy Consumption (Core Research Metrics) ---")
    print(f"  * Average Battery Voltage: {mean_v:.2f} V")
    print(f"  * Average Discharge Current:{mean_i:.2f} A")
    print(f"  * Average Electrical Power: {mean_p:.2f} W ({mean_p / 3.5:.2f} W/kg for 3.5 kg aircraft)")
    print(f"  * Total Consumed Energy:    {total_energy_j:.2f} Joules ({total_energy_wh:.3f} Wh)")

    print(f"\n⏱️ --- 4. NMPC Onboard Solver Real-time Performance ---")
    print(f"  * Mean Solve Time:       {mean_solve_ms:.2f} ms")
    print(f"  * Max Solve Time:        {max_solve_ms:.2f} ms")
    print(f"  * Control Loop Feasibility: {'100% REAL-TIME PASSED (< 10ms)' if max_solve_ms < 10.0 else 'CHECK LATENCY'}")
    print("=" * 75)

    return {
        "data": data,
        "eval_indices": eval_indices,
        "rmse_pos": rmse_pos,
        "mean_power": mean_p,
        "total_energy_j": total_energy_j,
        "filepath": filepath
    }

def try_plot_data(results):
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("\n[Notice] matplotlib is not installed in this environment. Text statistics generated above.")
        print("To generate publication-ready plots, run: pip install matplotlib pandas")
        return

    data = results["data"]
    eval_idx = results["eval_indices"]
    t = [data["time_sec"][i] for i in eval_idx]
    
    fig = plt.figure(figsize=(16, 10))
    fig.suptitle(f"UAV NMPC Real-Flight Benchmark: {os.path.basename(results['filepath'])}", fontsize=14, fontweight='bold')

    # Subplot 1: XY Trajectory
    ax1 = fig.add_subplot(2, 3, 1)
    if "ref_x" in data and any(data["ref_x"]):
        ax1.plot([data["ref_x"][i] for i in eval_idx], [data["ref_y"][i] for i in eval_idx], "r--", label="Reference", linewidth=1.8)
    ax1.plot([data["pos_x"][i] for i in eval_idx], [data["pos_y"][i] for i in eval_idx], "b-", label="Real Flight", linewidth=1.5)
    ax1.set_xlabel("X Position (m)")
    ax1.set_ylabel("Y Position (m)")
    ax1.set_title("XY Flight Trajectory")
    ax1.axis("equal")
    ax1.grid(True, linestyle="--", alpha=0.6)
    ax1.legend()

    # Subplot 2: Position Tracking Error
    ax2 = fig.add_subplot(2, 3, 2)
    ax2.plot(t, [data["err_x"][i] for i in eval_idx], label="Err X", alpha=0.7)
    ax2.plot(t, [data["err_y"][i] for i in eval_idx], label="Err Y", alpha=0.7)
    ax2.plot(t, [data["err_z"][i] for i in eval_idx], label="Err Z", alpha=0.7)
    ax2.plot(t, [data["err_pos_norm"][i] for i in eval_idx], "k-", label=f"3D Error (RMSE={results['rmse_pos']:.3f}m)", linewidth=1.8)
    ax2.set_xlabel("Time (s)")
    ax2.set_ylabel("Error (m)")
    ax2.set_title("Position Tracking Error")
    ax2.grid(True, linestyle="--", alpha=0.6)
    ax2.legend()

    # Subplot 3: Attitude Angles
    ax3 = fig.add_subplot(2, 3, 3)
    ax3.plot(t, [data["roll_deg"][i] for i in eval_idx], "r-", label="Roll (°)", alpha=0.8)
    ax3.plot(t, [data["pitch_deg"][i] for i in eval_idx], "g-", label="Pitch (°)", alpha=0.8)
    ax3.plot(t, [data["yaw_deg"][i] for i in eval_idx], "b-", label="Yaw (°)", alpha=0.6)
    ax3.set_xlabel("Time (s)")
    ax3.set_ylabel("Angle (°)")
    ax3.set_title("Attitude (Roll, Pitch, Yaw)")
    ax3.grid(True, linestyle="--", alpha=0.6)
    ax3.legend()

    # Subplot 4: Control Inputs (Body Rates & Specific Thrust)
    ax4 = fig.add_subplot(2, 3, 4)
    ax4.plot(t, [data["ctrl_wx"][i] for i in eval_idx], label="wx (rad/s)", alpha=0.7)
    ax4.plot(t, [data["ctrl_wy"][i] for i in eval_idx], label="wy (rad/s)", alpha=0.7)
    ax4.plot(t, [data["ctrl_wz"][i] for i in eval_idx], label="wz (rad/s)", alpha=0.7)
    ax4.plot(t, [data["ctrl_acc_z"][i] for i in eval_idx], "m-", label="a_T (m/s²)", linewidth=1.5)
    ax4.set_xlabel("Time (s)")
    ax4.set_ylabel("Control Command")
    ax4.set_title("NMPC Control Output")
    ax4.grid(True, linestyle="--", alpha=0.6)
    ax4.legend()

    # Subplot 5: Power & Cumulative Energy
    ax5 = fig.add_subplot(2, 3, 5)
    power_vals = [data.get("power_w", [0]*len(data["time_sec"]))[i] for i in eval_idx]
    ax5.plot(t, power_vals, "orange", label=f"Power (Avg={results['mean_power']:.1f}W)", linewidth=1.5)
    ax5.set_xlabel("Time (s)")
    ax5.set_ylabel("Power (W)", color="orange")
    ax5.grid(True, linestyle="--", alpha=0.6)
    ax5.legend(loc="upper left")

    # Subplot 6: Solver Latency
    ax6 = fig.add_subplot(2, 3, 6)
    solve_ms = [data.get("solve_time_ms", [0]*len(data["time_sec"]))[i] for i in eval_idx]
    ax6.plot(t, solve_ms, "teal", label="Solve Time (ms)", linewidth=1.2)
    ax6.axhline(5.0, color="r", linestyle="--", label="5ms Threshold")
    ax6.set_xlabel("Time (s)")
    ax6.set_ylabel("Solve Time (ms)")
    ax6.set_title("NMPC QP Solve Latency")
    ax6.grid(True, linestyle="--", alpha=0.6)
    ax6.legend()

    plt.tight_layout()
    plot_save_path = results["filepath"].replace(".csv", "_plot.png")
    plt.savefig(plot_save_path, dpi=200)
    print(f"\n[Success] 6-Panel Flight Benchmark Figure saved to: {plot_save_path}")

def main():
    pkg_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    default_dir = os.path.join(pkg_dir, "data", "jetson_flyrecord")

    if len(sys.argv) > 1:
        target_path = sys.argv[1]
    else:
        target_path = find_latest_csv(default_dir)
        if target_path is None:
            # Fallback to general data dir
            target_path = find_latest_csv(os.path.join(pkg_dir, "data"))

    if not target_path or not os.path.exists(target_path):
        print(f"Error: No CSV flight log files found in {default_dir}")
        print("Run 'ros2 run uav_mpc data_logger_node' during flight to generate CSV flight logs.")
        sys.exit(1)

    res = analyze_flight_data(target_path)
    if res:
        try_plot_data(res)

if __name__ == '__main__':
    main()
